package com.elka.servicedesk.other

enum class Work { REGISTRATION_USER, ADD_DIVISION, LOAD_DIVISIONS, AUTH_USER, LOAD_PROFILE, LOGOUT, LOAD_ADMINS, LOAD_LOGS, BLOCK_ADMIN, LOAD_USERS, BLOCK_USER, LOAD_ANALYSTS, UPDATE_USER }
