package com.elka.servicedesk.other

enum class Work {
  REGISTRATION_USER, ADD_DIVISION, LOAD_DIVISIONS, AUTH_USER, LOAD_PROFILE, LOGOUT, LOAD_LOGS, LOAD_USERS, BLOCK_USER, UPDATE_USER, REMOVE_DIVISION, CHANGE_USER_DIVISION, LOAD_INCIDENTS_REQUESTS, LOAD_ACCIDENTS
}
